//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGREQ.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sigreqEntities : DbContext
    {
        public sigreqEntities()
            : base("name=sigreqEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STACKHOLDER> STACKHOLDER { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<TIPOSTACKHOLDER> TIPOSTACKHOLDER { get; set; }
        public virtual DbSet<TIPOSTACKHOLDERID> TIPOSTACKHOLDERID { get; set; }
    }
}
