//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGREQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STACKHOLDER
    {
        public int STACKHOLDERID { get; set; }
        public string NOME { get; set; }
        public int TIPOSTACKHOLDERID { get; set; }
        public string TELEFONE { get; set; }
        public System.DateTime DATAREGISTRO { get; set; }
    
        public virtual TIPOSTACKHOLDER TIPOSTACKHOLDER { get; set; }
    }
}
